### ISSUE TITLE
Race condition because of class variables

### ISSUE THREAD

**Issue by tinloaf** [JulianKahnert/geizhals#5]
Hi, in

https://github.com/JulianKahnert/geizhals/blob/ff5f5ec1282efb1dadf74185e3f1bdb20a326b2f/geizhals/geizhals.py#L49-L53

you are making `device` (and `product_id` and `locale`, but that doesn't cause any errors) a class variable. This causes the `parse` methods of different `Geizhals` objects to use the same `Device` object, causing race conditions when they are run simultaneously. In fact, I experience this problem while tracking prices for two different products in Home Assistant - product A will randomly show up with the price of product B, and vice versa.

Did you intentionally make `device` a class variable? Otherwise I'd suggest moving lines 49-53 into `__init__`.

Thanks for your work!

**Comment by JulianKahnert** [comment]
Hey,
You are absolutely right! `device` and `product_id` should not be class variables. Thanks for looking into this problem. Would you like to create a pull request for this issue, since you found it?
Best regards,
Julian
